Add pipeline test for static build

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -47,6 +47,36 @@ jobs:
         run: cargo build --verbose
       - name: Run tests
         run: cargo test --verbose
+  build-ubuntu-static:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Setup build cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cargo/registry
+            ~/.cargo/git
+            target
+          key: ${{ runner.os }}-static-cargo-${{ hashFiles('**/Cargo.toml') }}
+      - name: Install musl compilation tools
+        run: sudo apt-get update && sudo apt-get install -y musl-tools
+      - name: Add static executable target
+        run: rustup target add x86_64-unknown-linux-musl
+      - name: Build
+        run: cargo build --verbose --target=x86_64-unknown-linux-musl
+      - name: Build release
+        run: cargo build --release --verbose --target=x86_64-unknown-linux-musl
+      - name: Check static executable
+        run: |
+          output=$(ldd target/x86_64-unknown-linux-musl/release/qkd_kme_server 2>&1 || true)
+          echo "$output"
+          if ! echo "$output" | grep -q "statically linked"; then
+            echo "ERROR: The binary is not statically linked."
+            exit 1
+          fi
+      - name: Run tests
+        run: cargo test --verbose --target=x86_64-unknown-linux-musl
   build-windows:
     runs-on: windows-latest
     steps:
